# --- !Ups  必要なスキーマの変換方法の記述
CREATE TABLE keep (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE problem (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE try (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  problem_id BIGINT(20) UNSIGNED NOT NULL, text TEXT NOT NULL, status TINYINT(3) UNSIGNED DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; CREATE TABLE try_task ( id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT, try_id BIGINT(20) UNSIGNED NOT NULL, text TEXT NOT NULL, status TINYINT(3) UNSIGNED DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE keep_tag (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tag_id BIGINT(20) UNSIGNED NOT NULL,
  keep_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE problem_tag (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tag_id BIGINT(20) UNSIGNED NOT NULL,
  problem_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE try_tag (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tag_id BIGINT(20) UNSIGNED NOT NULL,
  try_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tag (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tag_color_id BIGINT(20) UNSIGNED NOT NULL,
  name VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tag_color (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  color VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

# --- !Downs  Upsの変換をもとに戻す方法の記述
DROP TABLE keep, problem, try, try_task, keep_tag, problem_tag, try_tag, tag, tag_color;
